### ISSUE TITLE
Make DNSman avalable on f-droid

### ISSUE THREAD

**Issue by mimi89999** [otakuchiyan/DNSman#1]
To simplify installation and updates...

**Comment by otakuchiyan** [comment]
Have been submitted.

**Comment by mimi89999** [comment]
Thanks

**Comment by revuwa** [comment]
Thanks from my side, too.
Does probably anybody knows why the current version can't be built, instead of the previous one?
-> https://f-droid.org/wiki/page/io.github.otakuchiyan.dnsman

**Comment by popovn** [comment]
F-droid have 0.4 version
i cant to test newest version .... why?
