### ISSUE TITLE
Some interrogations 

### ISSUE THREAD

**Issue by LifeIsStrange** [otakuchiyan/DNSman#12]
Firstly thanks for this open source app :) 
I don't understund if DNS man work or don't work on my oneplus one lollipop, I have no root. 
It will be great to send a notification for say it work you now use the **.*.**.* DNS.

**Comment by otakuchiyan** [comment]
New notification was added.
Do you means "when DNS man doesn't work, pop a notification to show the errors"?

**Comment by LifeIsStrange** [comment]
Yes !

**Comment by otakuchiyan** [comment]
The function was added.

**Comment by LifeIsStrange** [comment]
Thanks !!
