### ISSUE TITLE
I cant add or edit

### ISSUE THREAD

**Issue by irregularisnotrandom** [otakuchiyan/DNSman#16]
The numerical space for the server constant.y fighting for keyboard pop up between numetical and standard keyboard , in a ssplit second it shows a list of addresses then closes the list. So basically i can neither or edit nor choose a sserver.

i am on lollipop arm7 and i am using the fdroid build.

Also it is not detecting the current dns properly, i hvce cryptdns and it is showing the server as 192.168.1.1 which is wrong.

**Comment by otakuchiyan** [comment]
It was lost focus when clicked EditText in ListView, I will try to fix it.
You can click again to open when keyboard is showing.

Current DNS is the output of `getprop`, if connected Wi-Fi, the output of getprop is follow router's DNS setting(192.168.1.1 is provided by router, right?)

**Comment by otakuchiyan** [comment]
Just tested, this bug is depending which input method was used.
When I using japanese input method, the list was flashed two times even keyboard was shown.
You can use another input method also.

**Comment by sniperle** [comment]
Same here, no input possible with my English keyboard layout, even if I touch the input box twice or more The only possible way to set a DNS server is to rotate the phone to landscape and even then it's a pain to set a DNS. 
Maybe an Asian keyboard layout does the job well.

Second problem is existing for me too. The DNS isn't set at all.

I'm on CM13, maybe Android 6 is to restrictive or maybe they did change something with DNS resolving in the system.

**Comment by otakuchiyan** [comment]
https://github.com/otakuchiyan/DNSman/releases/tag/v0.9-alpha2
Fixed. Tested by Google Pinyin Input.

**Comment by sniperle** [comment]
Thanks, the input is working well now  :-)

But if I set DNS servers for Mobile network the secondary DNS gets copied to WiFi and Bluetooth.

![screenshot_20160220-112654](https://cloud.githubusercontent.com/assets/3104188/13194477/ed53ba8e-d7c5-11e5-8f3c-1de5a742df03.png)

**Comment by otakuchiyan** [comment]
I may builded old sources, may newest source was fixed.
Try v0.9-beta1.

**Comment by sniperle** [comment]
Thanks again, beta1 is far better ;-)

Just one more small cosmetic issue. In settings there is an option "@2131034149" which seems to be the IPv6 switch.

![screenshot_20160220-124441](https://cloud.githubusercontent.com/assets/3104188/13194763/316d0efa-d7d0-11e5-8132-99fcd9531cd6.png)

**Comment by otakuchiyan** [comment]
Oh, thanks. I will fix it in next release.
