### ISSUE TITLE
[Request] quick view for current used DNS addresses

### ISSUE THREAD

**Issue by revuwa** [otakuchiyan/DNSman#3]
First of all, thanks a lot for that great app and your enthusiasm!

I just kindly wanted to ask, what do you think about an enhancement, that you do not have to tap on the single DNS1 / DNS2 points to view what values you have given, before?

Or better: a quick view, what are the current used DNS addresses.
This would be very cool, because I'm missing this kind of check in the app completely, (and have an additional app: https://github.com/bparmentier/DNSSetter installed to view the current DNS state).

To show what I am thinking of, I have made a theoretical picture:
![dnsman](https://cloud.githubusercontent.com/assets/7300276/9723243/41d4ef32-55bd-11e5-8716-7229482d765b.png)

**Comment by otakuchiyan** [comment]
OK, I will add this feature on next version.

**Comment by revuwa** [comment]
WOW, that sounds great; thanks in advance for that!
