### ISSUE TITLE
Lollipop

### ISSUE THREAD

**Issue by popovn** [otakuchiyan/DNSman#5]
**Doesn't work on Lollipop**
Sony Xperia z1 compact, rooted

but this works without root-asking:
https://play.google.com/store/apps/details?id=net.emrekoc.dnschanger

**Comment by MaxChinni** [comment]
@popovn [Dns Changer](https://play.google.com/store/apps/details?id=net.emrekoc.dnschanger) does not need root access because works on Wi-Fi only.

**Comment by otakuchiyan** [comment]
The "DNS changer" seems no used `VPNService` to changing DNS. I thought it was achieved by modify `/data/misc/wifi/ipconfig.txt`.
But this file is a binary, I tried to modify it but seems no any affect.
Actually, DNS man only used `setprop net.dnsX` to changing DNS.

**Comment by otakuchiyan** [comment]
Added firewall rules mode to changing DNS.
