### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by mimi89999** [otakuchiyan/DNSman#9]
When building I'm getting this error:
DNSman/app/src/main/java/io/github/otakuchiyan/dnsman/DNSManager.java:303: error: invalid method declaration; return type required
        public DNSBackgroundIntentService(){
               ^
1 error
:app:compileDebugJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJava'.

**Comment by otakuchiyan** [comment]
This class was not impleted yet.
